on: 
  push:
    branches:
      - main

name: "Trigger: Push action"
run-name: Shellcheck action
permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest 
    steps:
      - run: echo "Running shellchecks"
      - uses: actions/checkout@v4
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master

